### ISSUE TITLE
don't work for me.

### ISSUE THREAD

**Issue by thearabbit** [tuulbox/autoform-selectize#10]
I tried to install and use, but it don't work.
And then I tried to install `vazco:universe-autoform-select`, it work fine.
Please help me.

**Comment by izakfilmalter** [comment]
Can you go into greater detail for me. What did not work for you. What version of meteor are you using.

**Comment by thearabbit** [comment]
I use `Meteor 1.2.1`.

``` js
// Schema
............
module: {
        type: String,
        label: 'Module',
        autoform: {
            type: "universe-select",
            options: function () {
                return [
                    {label: '(Select One)', value: ''},
                    {label: 'A', value: 'A'},
                    {label: 'B', value: 'B'}
                ]
            }
        }
```

![2016-01-22_8-57-38](https://cloud.githubusercontent.com/assets/4495160/12500509/5a654652-c0e6-11e5-9b0e-5635a8641cf1.png)

**Comment by thearabbit** [comment]
I tried to install `vazco:universe-autoform-select`
![2016-01-22_9-24-36](https://cloud.githubusercontent.com/assets/4495160/12500890/fef7e51e-c0e9-11e5-8768-57ce2a8cacd0.png)

**Comment by thearabbit** [comment]
I think that, have problem with `.scss` style (don't load).

**Comment by izakfilmalter** [comment]
@thearabbit The `scss` files start with an `_` which means you have to explicitly import them. That means you can roll your own `css` without having to do a lot of overriding. If you want to use it as is make sure you are using https://github.com/fourseven/meteor-scss in your project and then import the file based on the documentation in his readme.

**Comment by izakfilmalter** [comment]
I do have a more uptodate scss file that I can push into the project as well.

**Comment by thearabbit** [comment]
Waiting you

**Comment by thearabbit** [comment]
I installed `fourseven:scss` add create `/client/stylesheet.scss` in my project

``` js
// stylesheet.scss
@import "{tuul:autoform-selectize}/stylesheets/_selectize.default.scss";
@import "{tuul:autoform-selectize}/stylesheets/_selectize.default.scss";
```

But show error

``` js
Errors prevented startup:

While processing files with fourseven:scss (for target web.browser):
/client/stylesheet.scss: Scss compiler error: File to import: {tuul:autoform-selectize}/stylesheets/_selectize.default.scss not found in file: D:/meteor-app/flatadmin/{}/client/stylesheet.scss


Your application has errors. Waiting for file change.
```

Please help me.

**Comment by thearabbit** [comment]
I tried to copy all of `.scss`, rename to `.css` and include it directly in my app.

``` js
/myapp
-----/client
------------/stylesheet
----------------------_selectize.default.css
----------------------_universe-autoform-select.css
```

It auto open like this
![2016-01-23_10-50-06](https://cloud.githubusercontent.com/assets/4495160/12528097/2344155c-c1bf-11e5-85ae-8adc4661bf27.png)

**Comment by izakfilmalter** [comment]
What version of `fourseven:scss` are you running?

**Comment by thearabbit** [comment]
Last (3.4.1) on atmosphere.

**Comment by thearabbit** [comment]
Could you import `.scss` directly?

**Comment by izakfilmalter** [comment]
I think this is a package issue. I'm looking into it. Hopefully will be
fixed by the end of the weekend.

**Comment by izakfilmalter** [comment]
Should work with the new version I pushed.

``` sass
@import "{tuul:autoform-selectize}/stylesheets/selectize.default";
@import "{tuul:autoform-selectize}/stylesheets/universe-autoform-select";
```

**Comment by thearabbit** [comment]
Now it work, but it's always open popup.

**Comment by thearabbit** [comment]
Now does it fix already?

**Comment by thearabbit** [comment]
Now I close this, if have problem I will open new.
