### ISSUE TITLE
Please fix some readme doc (install....).

### ISSUE THREAD

**Issue by thearabbit** [tuulbox/autoform-selectize#9]
Please fix some readme doc (install....).

**Comment by izakfilmalter** [comment]
Yes the readme needs to be updated. If you want to fork and post a pr that would be appreciated.

**Comment by thearabbit** [comment]
Sorry my English not good.

**Comment by izakfilmalter** [comment]
Updated readme. Let me know if this helps.

**Comment by thearabbit** [comment]
Look great, Very Interest.
Should your think about  package's name vs `field type on simpleSchema`.
Package name: `autoform-selectize`
Field type: `universe-select`

**Comment by izakfilmalter** [comment]
Ya haven't gotten around to changing the name there yet. Will get to it
shortly.
